apiVersion: v1
kind: ConfigMap
metadata:
  name: finpulse-app-config
  namespace: default
data:
  # Application configuration
  VITE_API_BASE_URL: "http://localhost:8055/api/v1"
  
  # Update these values based on your environment
  # VITE_API_BASE_URL: "https://api.yourdomain.com/api/v1"
